# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  tools:
    python: "3.8"

submodules:
  include: all

sphinx:
  configuration: doc/conf.py

python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - doc
  system_packages: true
